language: c

env:
  - PHP="PHP-7.1"
  - PHP="PHP-7.2"
  - PHP="master"

before_install:
  - echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart

before_script: ./travis/ci.sh

branches:
  only:
    - master

script:
  - ./php-src/sapi/cli/php php-src/run-tests.php -p `pwd`/php-src/sapi/cli/php --offline --show-diff --set-timeout 120 php-src/sapi/fpmi/tests
